fix
/home/wireshark/builders/trunk/ubuntu1204x64/build/epan/dissectors/packet-bssgp.c: In function de_bssgp_son_transfer_app_id:
/home/wireshark/builders/trunk/ubuntu1204x64/build/epan/dissectors/packet-bssgp.c:3173:12: error: variable next_tvb set but not used
[-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors



git-svn-id: http://anonsvn.wireshark.org/wireshark/trunk@46125 f5534014-38df-0310-8fa8-9805f1628bb7